[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FScanpy"
version = "1.0.0"
description = "Machine learning-based prediction of programmed ribosomal frameshifting sites"
readme = "README.md"
authors = [{name = "Yang Yuhao", email = "ykongxiang@qq.com"}]
maintainers = [{name = "Yang Yuhao", email = "ykongxiang@qq.com"}]
license = "MIT"
license-files = ["LICENSE"]
keywords = ["bioinformatics", "ribosomal-frameshifting", "PRF", "machine-learning", "FScanR"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy>=2.3",
    "pandas>=2.3",
    "scikit-learn==1.7.2",
    "matplotlib>=3.10",
    "joblib>=1.5",
    "biopython>=1.85",
    "torch>=2.5",
    "openpyxl"
]
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/ykongxiang/FScanpy-package"
Documentation = "https://github.com/ykongxiang/FScanpy-package/blob/master/tutorial/tutorial.md"
Repository = "https://github.com/ykongxiang/FScanpy-package"
Issues = "https://github.com/ykongxiang/FScanpy-package/issues"
Changelog = "https://github.com/ykongxiang/FScanpy-package/blob/master/CHANGELOG.md"
Publication = "https://doi.org/10.24272/j.issn.2095-8137.2025.648"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["FScanpy*"]

[tool.setuptools.package-data]
"FScanpy" = ["pretrained/*.pth", "pretrained/*.pkl"]
"FScanpy.data" = ["test_data/*"]
